version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh # terminate SpringBoot not connected to nginx
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # start new SpringBoot with the port not used by nginx
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # check availability of new SpringBoot
      timeout: 60
      runas: ec2-user